version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DEBUG: "True"
      DATABASE_ENGINE: "django.db.backends.sqlite3"
      DATABASE_NAME: "/app/db.sqlite3"